/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.Instant;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.InvoiceHeader;

/**
 *
 * @author Amr Mehanna
 */
public class AddInvoiceView extends javax.swing.JFrame {

    /**
     * Creates new form AddInvoiceView
     */
    private int invoiceNumberInt=0;
    public AddInvoiceView() {
        initComponents();
    }

    AddInvoiceView(InvoiveMainView aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tInvoiceDate = new javax.swing.JTextField();
        tCustomerName = new javax.swing.JTextField();
        okAddInvoice = new javax.swing.JButton();
        cancelAddInoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Invoice Date");

        jLabel2.setText("Customer Name");

        tInvoiceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tInvoiceDateActionPerformed(evt);
            }
        });

        tCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCustomerNameActionPerformed(evt);
            }
        });

        okAddInvoice.setText("OK");
        okAddInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAddInvoiceActionPerformed(evt);
            }
        });

        cancelAddInoice.setText("Cancel");
        cancelAddInoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddInoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(okAddInvoice))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelAddInoice)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tInvoiceDate)
                        .addComponent(tCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okAddInvoice)
                    .addComponent(cancelAddInoice))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tInvoiceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tInvoiceDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tInvoiceDateActionPerformed

    private void okAddInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAddInvoiceActionPerformed
        // TODO add your handling code here
        invoiceNumberInt +=1;
        String invoiceNumber =Integer.toString(invoiceNumberInt);
        //Date date1converted =Date.from(tInvoiceDate.getText());
         InvoiceHeader invHeader = new InvoiceHeader();
        //invHeader.setCustomerName(tCustomerName.getText());
        //invHeader.setInvoiceNumber(invoiceNumber);
       // Date date =Date.from(Instant.parse(tCustomerName.getText()));
        // invHeader.setDate(date);
        // String [] items ={invoiceNumber,tCustomerName.getText(),tInvoiceDate.getText()};
         //invSummary.setDate((Date.parse(tInvoiceDate.getText())));
        String [] items ={invoiceNumber,tCustomerName.getText(),tInvoiceDate.getText()};
       // DefaultTableModel tableModel=(DefaultTableModel)InvoiceMainView.tableHeader.gette();
       // tableModel.addRow(items);
       AddRowToJTable(items);
        
        
    }//GEN-LAST:event_okAddInvoiceActionPerformed

    private void cancelAddInoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddInoiceActionPerformed
        // TODO add your handling code here:
                this.setVisible(false);

    }//GEN-LAST:event_cancelAddInoiceActionPerformed

    private void tCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCustomerNameActionPerformed
     public static void AddRowToJTable(Object[] dataRow){
         DefaultTableModel model=(DefaultTableModel)InvoiveMainView.tableHeader.getModel();
       //DefaultTableModel model = (DefaultTableModel)tableSummary.getModel();
        model.addRow(dataRow);
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInvoiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInvoiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelAddInoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okAddInvoice;
    private javax.swing.JTextField tCustomerName;
    private javax.swing.JTextField tInvoiceDate;
    // End of variables declaration//GEN-END:variables
}
