/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.InvoiceHeader;
import model.InvoiceLine;

/**
 *
 * @author Amr Mehanna
 */
public class InvoiveMainView extends javax.swing.JFrame {
    
    



    /**
     * Creates new form InvoiveMainView
     */
    int flag =1;
    public InvoiveMainView() {
        
        initComponents();
        addlineBtn.setActionCommand("Save");
        deteteLineBtn.setActionCommand("Cancel");
        jMneuSave.setActionCommand("Open");
        jMenusaveFiles.setActionCommand("Save");
        deleteInvoiceBtn.setActionCommand("Delete");
        createInvoiceBtn.setActionCommand("Create");
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHeader = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableline = new javax.swing.JTable();
        jInvoiceTotal = new javax.swing.JLabel();
        jInvoiceNum = new javax.swing.JLabel();
        jCustomerName = new javax.swing.JLabel();
        jInvoiceDate = new javax.swing.JLabel();
        createInvoiceBtn = new javax.swing.JButton();
        deleteInvoiceBtn = new javax.swing.JButton();
        addlineBtn = new javax.swing.JButton();
        deteteLineBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSave = new javax.swing.JMenu();
        jMneuSave = new javax.swing.JMenuItem();
        jMenusaveFiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableHeader.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "Customer", "Date", "Total"
            }
        ));
        tableHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHeaderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableHeader);

        jLabel1.setText("Invoice Num");

        jLabel2.setText("Invoice total");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Invoice Date");

        tableline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO.", "Item Name", "Count", "Item Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(tableline);

        jInvoiceTotal.setText("-");

        jInvoiceNum.setText("-");

        jCustomerName.setText("-");

        jInvoiceDate.setText("-");

        createInvoiceBtn.setText("Create New Invoice");
        createInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceBtnActionPerformed(evt);
            }
        });

        deleteInvoiceBtn.setText("Delete Invoice");
        deleteInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInvoiceBtnActionPerformed(evt);
            }
        });

        addlineBtn.setText("New Line");
        addlineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addlineBtnActionPerformed(evt);
            }
        });

        deteteLineBtn.setText("Detete Line");
        deteteLineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deteteLineBtnActionPerformed(evt);
            }
        });

        jMenuSave.setText("File");

        jMneuSave.setText("Load Files");
        jMneuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMneuSaveActionPerformed(evt);
            }
        });
        jMenuSave.add(jMneuSave);

        jMenusaveFiles.setText("Save Data");
        jMenusaveFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenusaveFilesActionPerformed(evt);
            }
        });
        jMenuSave.add(jMenusaveFiles);

        jMenuBar1.add(jMenuSave);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createInvoiceBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteInvoiceBtn)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addlineBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deteteLineBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jInvoiceNum))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jInvoiceTotal)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInvoiceDate)
                            .addComponent(jCustomerName)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jInvoiceNum)
                            .addComponent(jCustomerName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jInvoiceTotal)
                            .addComponent(jInvoiceDate))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createInvoiceBtn)
                    .addComponent(deleteInvoiceBtn)
                    .addComponent(addlineBtn)
                    .addComponent(deteteLineBtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMneuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMneuSaveActionPerformed
        // TODO add your handling code he
        JFileChooser jLoad=new JFileChooser();
        if(jLoad.showOpenDialog(InvoiveMainView.this)== JFileChooser.APPROVE_OPTION){
            String path1 =jLoad.getSelectedFile().getPath();
            FileInputStream fileInputStream =null;
            
            try {
                fileInputStream=new FileInputStream(path1);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(InvoiveMainView.class.getName()).log(Level.SEVERE, null, ex);
            }
            int size=0;
            try {
                size = fileInputStream.available();
            } catch (IOException ex) {
                Logger.getLogger(InvoiveMainView.class.getName()).log(Level.SEVERE, null, ex);
            }
            //byte [] c=new byte[size];
            String g =Integer.toOctalString(size);
            tableHeader.setToolTipText(g);
            
            
            
        }
    }//GEN-LAST:event_jMneuSaveActionPerformed

    private void addlineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addlineBtnActionPerformed
        // TODO add your handling code here:
        new AddItemView(this).setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_addlineBtnActionPerformed

    private void jMenusaveFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenusaveFilesActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_jMenusaveFilesActionPerformed

    private void deteteLineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deteteLineBtnActionPerformed
    DefaultTableModel modelI=(DefaultTableModel)InvoiveMainView.tableline.getModel();

        modelI.removeRow(tableline.getSelectedRow());        // TOhandling code here:
    }//GEN-LAST:event_deteteLineBtnActionPerformed

    private void createInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceBtnActionPerformed
        // TODO add your handling code here:
        //AddInvoiceView addInvoiceView=new AddInvoiceView(this);
        //addInvoiceView.setVisible(true);
        
        new AddInvoiceView().setVisible(true);
    }//GEN-LAST:event_createInvoiceBtnActionPerformed

    private void tableHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHeaderMouseClicked
        // TODO add your handling code here:
      /*  DefaultTableModel model=(DefaultTableModel)tableHeader.getModel();

        if(!model.isSelectionEmpty()) {
        } else {
        }
        ///var data =tableHeader.getSelectedRow
        */
        InvoiceHeader invh=new InvoiceHeader();
      TableModel model1 = tableHeader.getModel();
        int indexs = tableHeader.getSelectedRow();
        String id = (String) model1.getValueAt(indexs, 0);
        String name = (String) model1.getValueAt(indexs, 1);
        String date = (String) model1.getValueAt(indexs, 2);
      //  String toTal = (String) model1.getValueAt(indexs, 3);
       // String toTal1 = Double.toString(getT);
        
        jInvoiceNum.setText(id);
        jCustomerName.setText(name);
        jInvoiceDate.setText(date);
        //jInvoiceTotal.setText("0");
        ArrayList<InvoiceLine> listTotal = null;
       // ArrayList<InvoiceLine> items1;
     // jInvoiceTotal.setText(Double.toString(invh.getTotal(listTotal)));


       /* String [] items ={id,name,date};
       DefaultTableModel  model2 = (DefaultTableModel) tableline.getModel();
        flag +=1;
        if (flag>2){
       model2.removeRow(0);
        }
          //      model2.addRow(items);

        
        model2.addRow(items);
        */
        
     


        


    }//GEN-LAST:event_tableHeaderMouseClicked

    private void deleteInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInvoiceBtnActionPerformed
        DefaultTableModel model=(DefaultTableModel)InvoiveMainView.tableHeader.getModel();
        model.removeRow(tableHeader.getSelectedRow());
       
    }//GEN-LAST:event_deleteInvoiceBtnActionPerformed
        public static void AddRowToJTable(Object[] dataRow){
        // TableModel model=(DefaultTableModel)InvoiveMainView.tableline.getModel();
       //DefaultTableModel model = (DefaultTableModel)tableSummary.getModel();
     // model.addRow(dataRow);
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiveMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiveMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiveMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiveMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiveMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addlineBtn;
    public javax.swing.JButton createInvoiceBtn;
    public javax.swing.JButton deleteInvoiceBtn;
    public javax.swing.JButton deteteLineBtn;
    public javax.swing.JLabel jCustomerName;
    public javax.swing.JLabel jInvoiceDate;
    public javax.swing.JLabel jInvoiceNum;
    public javax.swing.JLabel jInvoiceTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuSave;
    private javax.swing.JMenuItem jMenusaveFiles;
    private javax.swing.JMenuItem jMneuSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tableHeader;
    public static javax.swing.JTable tableline;
    // End of variables declaration//GEN-END:variables
}
